
## 장고 기본설정이후 다시 docker-compose up --build 명령 실행하기
services:
  db:
    build:
      context: ./postgre  # PostgreSQL 이미지
    restart: always
    # container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}         #  데이터베이스 이름
      - POSTGRES_USER=${POSTGRES_USER}      # 데이터베이스 사용자
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # 데이터베이스 비밀번호
    ports:
      - "5432:5432"  # 외부에서 접근 가능하도록 포트 설정
    volumes:
      - ./postgres_data:/var/lib/postgresql/data   
    env_file:
      - .env

  web:
    build:
      context: ./app  # Django 앱이 위치한 경로
    # container_name: web
    restart: always
    volumes:
      - ./app:/app   
    ports:
      - "8000:8000"  
    environment:
      - POSTGRES_URL=${POSTGRES_URL}  
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}   
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
    command: ["./entrypoint.sh"]
      # command: python manage.py runserver 0.0.0.0:8000 
    # command: bash -c "python & tail -f /dev/null"

volumes:
  postgres_data:
