# Generated by Django 5.1.1 on 2024-11-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartvalue',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
