# Generated by Django 5.1.1 on 2024-11-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chartvalue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartvalue',
            name='good_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
