# Generated by Django 5.1.1 on 2024-11-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_chartvalue_good_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartvalue',
            name='EPS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartvalue',
            name='매물대1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartvalue',
            name='매물대2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartvalue',
            name='부채비율',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartvalue',
            name='상장주식수',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartvalue',
            name='액면가',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartvalue',
            name='유동주식수',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartvalue',
            name='유보율',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
