# Generated by Django 5.1.1 on 2024-11-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_chartvalue_pre_vol_chartvalue_vol20'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('recommend_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
    ]
