# Generated by Django 5.1.1 on 2024-11-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
